@baseUrl = http://localhost:3500
@authToken ={{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name":"mattheus",
  "email":"mattheus1@mail.com",
  "password":"1234"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email":"mattheus1@mail.com",
  "password":"1234"
}

###

# @name create_Questions
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email":"mattheus1@mail.com",
  "password":"1234"
}

