version: '3.8'

services:
  postgres:
    container_name: nest-pg-rocket
    image: postgres
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: mazza
      POSTGRES_PASSOWRD: db1234
      POSTGRES_DB: nest-rocket
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres